name: hugo-remote

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          npm install -g postcss-cli
          npm install -g autoprefixer
          npm install -g postcss
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "latest"
          extended: true
      - name: Build
        run: make deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_branch: master
          publish_dir: ./public
          external_repository: fundor333/digitaltearoom.github.io
          commit_message: 🚀 Deploy with hugo-remote
